### ISSUE TITLE
[Bug]: AWS PCA Issuer Pod does not assume AWS IAM Role using Helm Deployment

### ISSUE THREAD

**Issue by geoffo-dev** [cert-manager/aws-privateca-issuer#105]
### Describe the expected outcome

When deploying the pod using a helm chart and manually creating the ServiceAccount, the pod should inherit the permissions assigned to the IAM role specified in the manually created ServiceAccount and be able to requested certificates.

### Describe the actual outcome

The Pod appears to not inherit the correct permissions and fails to get the certificate.

``` bash
cert-manager  The certificate request has failed to complete and will be retried: failed to request certificate from 
PCA: operation error ACM PCA: IssueCertificate, https response error StatusCode: 400, RequestID: e1e844fb-1af5-4d63-9872-bfe9e627537e, api error 
AccessDeniedException: User: arn:aws:sts::xxxxxx:assumed-role/xxxxxxxx/xxxxxx is not authorized to perform: acm-pca:IssueCertificate 
on resource: arn:aws:acm-pca:eu-west-2:xxxx:certificate-authority/xxxxx because no resource-based policy 
allows the acm-pca:IssueCertificate action
```

It appears that the pod has the correct ServiceAccount role as it is getting the token?

<img width="907" alt="Screenshot 2021-12-22 at 10 40 10" src="https://user-images.githubusercontent.com/53539843/147080361-b6f0b593-0e81-4b8c-8c3c-0b8e53597907.png">

### Steps to reproduce

Deployment of the PCA Issuer Helm Chart using terraform 

``` yaml
resource "helm_release" "eks_aws_pca" {
  name       = "${var.site_name}-aws-pca"
  chart      = "aws-privateca-issuer"
  repository = "https://cert-manager.github.io/aws-privateca-issuer"
  version    = var.aws_pca_helm_version
  namespace  = local.aws_pca_namespace

  set {
    name  = "installCRDs"
    value = "true"
  }

  set {
    name  = "image.repository"
    value = var.aws_privateca_issuer_image
  }

  set {
    name  = "image.tag"
    value = var.aws_privateca_issuer_tag
  }

  set {
    name  = "serviceAccount.create"
    value = false
  }

  set {
    name  = "serviceAccount.name"
    value = module.eks_aws_pca_irsa.service_account_name
  }

  set {
    name  = "approverRole.namespace"
    value = local.cert_manager_namespace
  }

  set {
    name  = "approverRole.serviceAccountName"
    value = local.cert_manager_service_account_name
  }

}
```

Deploying version 1.0.0 of the Helm Chart and Version 1.0.0 of the aws-privateca container

### Version

v1.0.0

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Authentication Issue

### Severity

Severity 2

**Comment by Varunvallabhan52** [comment]
Thank you for raising this issue with the AWS Private CA Issuer plugin. We will review your submission and respond back to you here as soon as possible.

**Comment by divyansh-gupta** [comment]
Could you please share your IAM policy as well, to make sure the correct acm-pca permissions are in place?

**Comment by geoffo-dev** [comment]
Hi @divyansh-gupta, so I have been getting the image there with the image tag of 1.0.0. Annoyingly we have to bring the image in and scan it into our own docker repo... that is why they are hardcoded - apologies.

Yes sorry that is correct we have a share PCA through RAM - so I have tried a normal admin with the certificates and it looks like they can request a certificate with no issues.

```json
{
    "Statement": [
        {
            "Action": [
                "acm-pca:IssueCertificate",
                "acm-pca:GetCertificateAuthorityCertificate",
                "acm-pca:GetCertificate",
                "acm-pca:DescribeCertificateAuthority"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:acm-pca:eu-west-2:xxxxxx:certificate-authority/{rootpcaid}",
            "Sid": "awspcaissuer"
        }
    ],
    "Version": "2012-10-17"
} 
```
Our policy on RAM is here:
<img width="1157" alt="Screenshot 2021-12-22 at 17 08 05" src="https://user-images.githubusercontent.com/53539843/147129574-6c5fe28f-3f44-41ca-acb1-ca94ee7fd355.png">

**Comment by anbaig** [comment]
So the default RAM permission is going to only allow you to issue certificates that have the template: 
`acm-pca:::template/EndEntityCertificate/V1`

This chart in the README shows the mapping of CertManager usage types to template ARNS: https://github.com/cert-manager/aws-privateca-issuer#mapping-cert-manager-usage-types-to-aws-pca-template-arns

You will need to ensure that the certificates you are trying to issue have both ClientAuth and ServerAuth set to get the right templateARN to be used.

**Comment by geoffo-dev** [comment]
@anbaig - you are correct!! that worked - adding both in resulted in a success!

Thanks for the quick help and sorry that I didnt get that right...! Apologies!!

**Comment by anbaig** [comment]
Glad that worked for you, please open a separate issue if you run into anymore problems using the plugin.
