### ISSUE TITLE
[Known Issue]: Incorrect Certificate Validity for certificates with specified validity duration. (v1.0.0/v1.1.0)

### ISSUE THREAD

**Issue by varunvallabhan52** [cert-manager/aws-privateca-issuer#121]
During the release of v1.0.0 in Nov 2021, the plugin would add 30 days as the validity period for every certificate as a default for certificates with no validity duration specified, with this a bug was introduced which would add 30 days to the validity period on top of the specified validity duration; this was carried forward to v1.1.0 as well. This issue has been rectified in v1.2.0 (For more information please look in to [PR](https://github.com/cert-manager/aws-privateca-issuer/pull/111/files). If the incorrect validity is a breaking issue then revoke the old certificates, move to version v1.2.0, and issue new certs.

**Comment by Hamidhasan** [comment]
This issue has been fixed since February 11th, and only applies to older plugin versions. Moving to v.1.2.0 or later will rectify the issue. Resolving.
