### ISSUE TITLE
[Bug]: Helm chart use latest image instead of appVersion

### ISSUE THREAD

**Issue by dsch** [cert-manager/aws-privateca-issuer#135]
### Describe the expected outcome

Installing the Helm chart should use the image matching the `appVersion`.

This will allow a reproducible deployment.

### Describe the actual outcome

The latest image get always used, which will lead to unexpected upgrade in case the pod gets restarted.

### Steps to reproduce

`helm template pca-issuer awspca/aws-privateca-issuer --version 1.2.0`

Output:
```
...
     containers:
        - name: aws-privateca-issuer
          image: "public.ecr.aws/k1n1h4h4/cert-manager-aws-privateca-issuer:latest"
...
```

Note:
I'm aware of the possibility to set image.tag to "" in the values file to fallback to the Chart.AppVersion.

### Version

>= 1.0.0

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Other

### Severity

Severity 4

**Comment by bmsiegel** [comment]
Thank you for raising this issue with the AWS Private CA Issue plugin. We are currently reviewing #126 which should solve this issue. Will post here when it has been merged in.

**Comment by Hamidhasan** [comment]
Thanks again for raising this issue, we've merged in https://github.com/cert-manager/aws-privateca-issuer/pull/151 which is a follow-up to sarahhodne@'s original PR #126. The next step would be to cut a new release, but if building from source, this change is now available.

**Comment by dsch** [comment]
release with [v1.2.1 ](https://github.com/cert-manager/aws-privateca-issuer/releases/tag/v1.2.1)
