### ISSUE TITLE
[Bug]: Can's issue certificate from a shared private CA

### ISSUE THREAD

**Issue by kumar-shantanu** [cert-manager/aws-privateca-issuer#211]
### Describe the expected outcome

AWSPCAClusterIssuer should be able to provision certificate

### Describe the actual outcome

Our private CA authority is hosted in the networking account and has been shared with other accounts(let's call it dev-1) here. We can manually generate the certs by logging into the dev-1 account. 

Now when I create an AWSPCAClusterIssuer, the CA arn I am specifying contains the network account's id (which is obvious), and when I try to create the cert using this certificate it errors out with the below error, 

"level":"error","ts":1657793954.0080278,"logger":"controllers.CertificateRequest","msg":"failed to request certificate from PCA","certificaterequest":"default/example-com-f9v6w","error":"operation error ACM PCA: IssueCertificate, https response error StatusCode: 400, RequestID: b6cd6e9b-9e6a-42b9-a96f-38806a3ffffb, api error AccessDeniedException: User: arn:aws:sts::XXXXXXXX:assumed-role/shared-dev-1-cert-manager/1657793931500012209 is not authorized to perform: acm-pca:IssueCertificate on resource: arn:aws:acm-pca:eu-west-2:YYYYYYY:certificate-authority/68275bf7-8147-4620-ba7d-4fecf3f234e0 because no resource-based policy allows the acm-pca:IssueCertificate action","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

### Steps to reproduce

Install certmanager on eks
Try to use a shared private CA for cert creation

### Version

v1.2.2

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Authentication Issue

### Severity

Severity 2

**Comment by divyansh-gupta** [comment]
Hi, could you please post the relevant portion of the policy you are using for arn:aws:sts::XXXXXXXX:assumed-role/shared-dev-1-cert-manager/1657793931500012209, and the policy or RAM permission attached to your CA?

And what template type are you issuing with? Cross-account supports a limited set of template types. The plugin picks the template type based off the Usage Type you specify. Check this section in our Readme for information: Mapping Cert-Manager Usage Types to AWS PCA Template Arns.

Thank you.

**Comment by kumar-shantanu** [comment]
Hi @divyansh-gupta , the policy looks like this, 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "awspcaissuer",
            "Effect": "Allow",
            "Action": [
                "acm-pca:IssueCertificate",
                "acm-pca:GetCertificate",
                "acm-pca:DescribeCertificateAuthority"
            ],
            "Resource": "*"
        }
    ]
}
 and RAM permission attached to the CA is the one provided by AWS permission library named AWSRAMDefaultPermissionCertificateAuthority

**Comment by divyansh-gupta** [comment]
Thank you. That RAM policy is:

```
[
  {
    "Effect": "Allow",
    "Action": [
      "acm-pca:IssueCertificate"
    ],
    "Condition": {
      "StringEquals": {
        "acm-pca:TemplateArn": "arn::acm-pca:::template/EndEntityCertificate/V1"
      }
    }
  },
  {
    "Effect": "Allow",
    "Action": [
      "acm-pca:DescribeCertificateAuthority",
      "acm-pca:GetCertificate",
      "acm-pca:GetCertificateAuthorityCertificate",
      "acm-pca:ListPermissions",
      "acm-pca:ListTags"
    ]
  }
]
```

Are you issuing a `arn::acm-pca:::template/EndEntityCertificate/V1` through the plugin, based off the `Mapping Cert-Manager Usage Types to AWS PCA Template Arns` section of the README?

**Comment by divyansh-gupta** [comment]
Hi @kumar-shantanu, no problem, happy to help. Each Certificate CRD has an optional `usages` section, as defined in https://cert-manager.io/docs/usage/certificate/#creating-certificate-resources. The plugin translates those usages to templateArns based off this chart: https://github.com/cert-manager/aws-privateca-issuer#mapping-cert-manager-usage-types-to-aws-pca-template-arns

Your user is authorized to issue an EndEntityCertificate/V1 certificate. The chart shows that you need `ClientAuth, ServerAuth` usages for that. Here is an example of what you need to add to your CRD to do that: https://github.com/cert-manager/aws-privateca-issuer/blob/16fdb566060577882a76da89239e439422ed856b/config/examples/certificates/ecdsa-521.yaml#L17-L19

Let me know if that works out for you.

**Comment by kumar-shantanu** [comment]
Ah, Thank you very much @divyansh-gupta  it worked like a chart.
