### ISSUE TITLE
CA Certificates are not currently supported via the PCA external issuer

### ISSUE THREAD

**Issue by akunszt** [cert-manager/aws-privateca-issuer#23]
As the code says at:
https://github.com/jniebuhr/aws-pca-issuer/blob/e5e5d80ede895ecc079ffa3bb3f2e0821b8d6c3b/pkg/controllers/certificaterequest_controller.go#L136

Is it an intentional limitation? Or is it still in progress? If yes than do you have any timeline for it?

We would like to issue a sub-ordinate CA signed by ACMPCA. We can do that using `aws` or the web console but it would be nice if `aws-pca-issuer` supports this too.

**Comment by caleygoff-invitae** [comment]
Is there any movement on prioritizing this? It would be really nice to be able to use this with istio-csr to manage the tls certs istio requires that are issued by a private pca.

**Comment by sepulworld** [comment]
I started work on this here: https://github.com/cert-manager/aws-privateca-issuer/pull/55 please review and let me know if you want to change anything or if you want me to add more tests (I can add CA cert creation for Cluster issuer level if you would like as well).

**Comment by anbaig** [comment]
This is now supported in the newest release; v1.1.0! https://github.com/cert-manager/aws-privateca-issuer/releases/tag/v1.1.0
