### ISSUE TITLE
[Feature Request]: Documentation of useage with ingress annotations

### ISSUE THREAD

**Issue by marcokuznik** [cert-manager/aws-privateca-issuer#267]
### Describe why this change is needed

Hello aws-privateca-issier team,

I tried to use aws-privateca-issuer with annotations of ingress resources, but didn't find a documentation how to apply the appotations to issue certificates automatically. 

I configured my issuer as follows:
- apiVersion: awspca.cert-manager.io/v1beta1
  metadata:
    annotations:
       name: my-root-ca
  kind: AWSPCAClusterIssuer
  spec:
    arn: arn:aws:acm-pca:eu-central-1:XXXXXX:certificate-authority/XXXXXX
    region: eu-central-1

I used following annotations in the ingress ressource:
cert-manager.io/cluster-issuer: my-root-ca

But no certificate is issued. When i create the certificatate and ingress ressources manually the the cluster gets the tls certificate provisioned by the private acm and everything is fine but with annotations I was not able to issue certificates.

Can you give me advice how to annotate the ingress to issue certificates automatically? Cert-manager annotation documentation has a view references to aws-privateca-issuer, but it is not clear how to use them.

using cert-manager version 1.11.0 and aws-privateca-issuer 1.2.4

Can you provide some documentation or any advices to make this work?

best regards,
Marco

**Comment by divyansh-gupta** [comment]
Updated the README to describe this issue and how to resolve it.

Resolving this issue.
