### ISSUE TITLE
security 

### ISSUE THREAD

**Issue by anoora17** [cert-manager/aws-privateca-issuer#274]
### Describe the expected outcome

security scan  regards google.golang.org/protobuf:v.181.1  HIGH Parsing invalid messages can panic. Parsing a text-format message which contains a potential number consisting of a minus sign, one or more characters of whitespace, and no further input will cause a panic. CLOSED None Provided

### Describe the actual outcome

please upgrade the package to Version:protobuf 1.29.1 or 1.31.1

### Version

1.2.5

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Authentication Issue

### Severity

Severity 1

**Comment by divyansh-gupta** [comment]
Thanks for the issue - what AWS region are you operating in?

**Comment by bmsiegel** [comment]
https://github.com/cert-manager/aws-privateca-issuer/pull/276

Working on releasing this

**Comment by bmsiegel** [comment]
v1.2.6 released the fix for this security issue.
