### ISSUE TITLE
[Bug]: awspca-issuer not using secretRef to obtain CA

### ISSUE THREAD

**Issue by walterchangsmoothstack** [cert-manager/aws-privateca-issuer#281]
### Describe the expected outcome

Expected the AWSPCAIssuer with a secretRef to use access key and secret key from secret to obtain a CA from AWS Private CA.

### Describe the actual outcome

Certificates issued to AWSPCAIssuer stuck in READY state "FALSE." Logs from the aws-prviateca-issuer pod suggest that the pod is trying to use STS to authenticate with AWS. I am unable to setup OIDC in my setup, so I must resort to using the secretRef in the Issuer CRD for authentication. The CA is in AWS U.S. gov cloud. 

Output from describe awspcaissuer:
Name:         aws-pca-issuer-istio
Namespace:    istio-system
Labels:       <none>
Annotations:  <none>
API Version:  awspca.cert-manager.io/v1beta1
Kind:         AWSPCAIssuer
Spec:
  Arn:     ${ARN}
  Region:  ${REGION}
  Secret Ref:
    Name:       pca-secret
    Namespace:  istio-system
Events:         none

### Steps to reproduce

**Install cert-manager:**
helm install cert-manager jetstack/cert-manager -n cert-manager

**Install aws-privateca-issuer:**
helm install awspca/aws-privateca-issuer -n cert-manager

Create a secret pca-secret with the following definition:
apiVersion: v1
kind: Secret
metadata:
  name: pca-secret
  namespace: default
data:
  AWS_ACCESS_KEY_ID: {{BASE64_ACCESSKEY}}
  AWS_SECRET_ACCESS_KEY: {{BASE64_SECRETKEY}}

Create a certificate authority in AWS Private CA and issue a certificate for it. Use the CA arn in the following AWSPCAIssuer resource:

apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAIssuer
metadata:
 name: aws-pca-issuer-istio
 namespace: istio-system
spec:
  arn: ${ARN}
  region: ${REGION}
  secretRef:
    name: pca-secret
    namespace: istio-system

### Relevant log output

```shell
{"level":"error","ts":"2023-08-16T19:55:37Z","logger":"controllers.GenericIssuer","msg":"failed to sts.GetCallerIdentity","genericissuer":"istio-system/aws-pca-issuer-istio","error":"operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://sts.<REGION>.amazonaws.com/\": net/http: invalid header field value for \"Authorization\"","stacktrace":"github.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*GenericIssuerReconciler).Reconcile\n\t/workspace/pkg/controllers/genericissuer_controller.go:92\ngithub.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*AWSPCAIssuerReconciler).Reconcile\n\t/workspace/pkg/controllers/awspcaissuer_controller.go:57\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

### Version

aws-privateca-issuer-v1.2.5
cert-manager-v1.12.0

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Authentication Issue

### Severity

Severity 1

**Comment by shankara-n** [comment]
Thanks for opening the bug. We are looking into it now. Will post an update shortly.

**Comment by shankara-n** [comment]
Your secret ref namespace and secret namespace seem to be different. Is that accurate?

**Comment by walterchangsmoothstack** [comment]
> Your secret ref namespace and secret namespace seem to be different. Is that accurate?

Sorry, that was a typo that I made in the bug report. The secret is actually in the istio-system namespace.

**Comment by shankara-n** [comment]
Are you able to make any other AWS API calls using the same secret setup? That would confirm that the credentials are correct and STS  works without issue, cuz from the error it looks like a credentials issue.

**Comment by walterchangsmoothstack** [comment]
Hi, sorry I have not used AWS API calls with Kubernetes secrets before. How could I setup an AWS API call using that secret setup? I have confirmed from using the AWS cli that the credentials are valid. Also, for the secret I did `echo <ACCESS_KEY> | base64` to obtain the base64 encoded text.

**Comment by divyansh-gupta** [comment]
We do have automated test cases running that check for the K8s Secret authentication path working: https://github.com/cert-manager/aws-privateca-issuer/actions/runs/5728383042/job/15522863583#step:15:1

**Comment by walterchangsmoothstack** [comment]
Hi, you were right, the issue was due to the credentials. I must have had some extra whitespace in the base64 text. This thread helped me find out the typo.
https://github.com/external-secrets/external-secrets/issues/2533
