### ISSUE TITLE
[Feature Request]: Support ARM64 architecture

### ISSUE THREAD

**Issue by SQUIDwarrior** [cert-manager/aws-privateca-issuer#283]
### Describe why this change is needed

The published images are only built for AMD64. The use of ARM64 nodes (such as AWS' Graviton) are becoming increasingly common and this would be extremely useful to have.

### Describe solutions and alternatives considered (optional)

This tool should be built for both ARM64 and AMD64 platforms, and the published images should support both.

**Comment by dcamzn** [comment]
Hi @SQUIDwarrior we plan to support ARM64 architecture in the future, but they are not on the roadmap, yet. We will respond back to threads requesting this when we have a timeline.

**Comment by sidewinder12s** [comment]
Could you add amd64 node affinity/selector to the helm chart in the mean time?

**Comment by MirkoPiaggesi** [comment]
Hi @dcamzn ,

Sorry for asking, but maybe after almost 1y something has changed... any updated ETA for ARM support? 

Thank you

**Comment by dcamzn** [comment]
Hi @MirkoPiaggesi , we were trying to get testing updated to support ARM in Q2 2024, but we won't be able to hit that timeline. We are targeting Q3.
