### ISSUE TITLE
[Bug]: Issuer is not ready and certificate creation fails

### ISSUE THREAD

**Issue by hiroo-kitamura** [cert-manager/aws-privateca-issuer#292]
### Describe the expected outcome

I created a certificate included in [examples](https://github.com/cert-manager/aws-privateca-issuer/tree/main/config/examples) according to the [README](https://github.com/cert-manager/aws-privateca-issuer/blob/main/README.md) on OpenShift, but the creation fails.

I couldn't find any clear restrictions in the README, but is it possible to run this project on systems other than Amazon EKS, such as OpenShift or vanilla kubernetes?
If it is possible to make it work, how can I link the IAM Role listed in Configuration to the Service Account?

### Describe the actual outcome

The following error occurs when creating a certificate resource.
```
  Warning  Failed     60s   cert-manager-certificates-issuing          The certificate request has failed to complete and will be retried: issuer is not ready
```

### Steps to reproduce

* Install `cert-manager Operator for Red Hat OpenShift` on OpenShift 4.12
* Install aws-privateca-issuer
* Create [secret and issuer resources](https://github.com/cert-manager/aws-privateca-issuer/tree/main/config/examples/config)
* Create [certificate resource](https://github.com/cert-manager/aws-privateca-issuer/blob/main/config/examples/certificates/rsa-2048.yaml)

### Relevant log output

```shell
* secret

$ oc describe secret/example
Name:         example
Namespace:    cert-manager
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
AWS_ACCESS_KEY_ID:      21 bytes
AWS_SECRET_ACCESS_KEY:  41 bytes
```

* awspcaissuer
```
$ oc describe awspcaissuer.awspca.cert-manager.io/example
Name:         example
Namespace:    cert-manager
Labels:       <none>
Annotations:  <none>
API Version:  awspca.cert-manager.io/v1beta1
Kind:         AWSPCAIssuer
Metadata:
...snip...
Spec:
  Arn:     <***>
  Region:  <***>
  Secret Ref:
    Name:       example
    Namespace:  cert-manager
Events:         <none>
```

* certificate
```
$ oc describe certificate.cert-manager.io/rsa-cert-2048
Name:         rsa-cert-2048
Namespace:    cert-manager
Labels:       <none>
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
...snip...
Spec:
  Common Name:  <***>
  Dns Names:
    <***>
  Duration:  2160h0m0s
  Issuer Ref:
    Group:  awspca.cert-manager.io
    Kind:   AWSPCAIssuer
    Name:   example
  Private Key:
    Algorithm:   RSA
    Size:        2048
  Renew Before:  360h0m0s
  Secret Name:   rsa-cert-2048
  Subject:
    Organizations:
      aws
  Usages:
    server auth
    client auth
Status:
  Conditions:
    Last Transition Time:    2023-10-05T07:00:24Z
    Message:                 The certificate request has failed to complete and will be retried: issuer is not ready
    Observed Generation:     1
    Reason:                  Failed
    Status:                  False
    Type:                    Issuing
    Last Transition Time:    2023-10-05T07:00:23Z
    Message:                 Issuing certificate as Secret does not exist
    Observed Generation:     1
    Reason:                  DoesNotExist
    Status:                  False
    Type:                    Ready
  Failed Issuance Attempts:  1
  Last Failure Time:         2023-10-05T07:00:24Z
Events:
  Type     Reason     Age   From                                       Message
  ----     ------     ----  ----                                       -------
  Normal   Issuing    61s   cert-manager-certificates-trigger          Issuing certificate as Secret does not exist
  Normal   Generated  60s   cert-manager-certificates-key-manager      Stored new private key in temporary Secret resource "rsa-cert-2048-fgn9w"
  Normal   Requested  60s   cert-manager-certificates-request-manager  Created new CertificateRequest resource "rsa-cert-2048-4r49c"
  Warning  Failed     60s   cert-manager-certificates-issuing          The certificate request has failed to complete and will be retried: issuer is not ready
```

* CertificateRequest
```
$ oc describe CertificateRequest rsa-cert-2048-4r49c
Name:         rsa-cert-2048-4r49c
Namespace:    cert-manager
Labels:       <none>
Annotations:  cert-manager.io/certificate-name: rsa-cert-2048
              cert-manager.io/certificate-revision: 1
              cert-manager.io/private-key-secret-name: rsa-cert-2048-fgn9w
API Version:  cert-manager.io/v1
Kind:         CertificateRequest
Metadata:
...snip...
Spec:
  Duration:  2160h0m0s
  Extra:
    authentication.kubernetes.io/pod-name:
      cert-manager-5fb76fbd98-mb62n
    authentication.kubernetes.io/pod-uid:
      e657c63c-f440-4b5c-a77a-880ef7620d66
  Groups:
    system:serviceaccounts
    system:serviceaccounts:cert-manager
    system:authenticated
  Issuer Ref:
    Group:  awspca.cert-manager.io
    Kind:   AWSPCAIssuer
    Name:   example
  Request:  <***>
  UID:      6e352c4d-4ab9-4ea6-b226-eea03a757b98
  Usages:
    server auth
    client auth
  Username:  system:serviceaccount:cert-manager:cert-manager
Status:
  Conditions:
    Last Transition Time:  2023-10-05T07:00:24Z
    Message:               issuer is not ready
    Reason:                Failed
    Status:                False
    Type:                  Ready
Events:
  Type     Reason  Age   From                     Message
  ----     ------  ----  ----                     -------
  Warning  Failed  111s  awspcaissuer-controller  issuer is not ready
```
```


### Version

v1.2.5

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Build Issues

### Severity

Severity 1

**Comment by Hamidhasan** [comment]
Thank you for raising this issue with the AWS Private CA Issuer plugin. We will review your submission and respond back to you here as soon as possible.

**Comment by Hamidhasan** [comment]
It should be possible to get the plugin to work by simply using the access key / secret; EKS is not mandatory. 

Are you sure your AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY values are Base64 Encoded? They will not work otherwise.

**Comment by Hamidhasan** [comment]
I tried for a few times to reproduce the issue -- ultimately, was not able to. A few times I did actually reproduce the situation you had, but in my case, I was trying it with a generated access key id / secret key and I think my credentials were expired when it tried to issue the cert. I also did it when I did not base64 encode the creds and got the issue you experienced. Also, I did it a few times where the secret name mismatched (it does not inform you if the secret fails to parse when creating/describing the Issuer, it will just fail the cert issuance). It took me a few tries admittedly, but I did get it to work.

To make it easier to test using the access key method, try using it with a permanent one, i.e. one created via https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey, instead of generated temporary credentials. This made it much easier, and worked for me on the first try.

**Comment by hiroo-kitamura** [comment]
Thank you for the answer.

> Can you comment on how you generated the access key and secret key?

I encoded these with the following commands.
I also performed a decoding check.
```
$ echo <AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY> | base64
<Encoded ID or KEY>
$ echo <Encoded ID or KEY> | base64 -d
<AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY
```

> Did you do it via temp credentials (usually there is an AWS_SESSION_TOKEN with this method), or did you do it with an Access Key created in IAM (i.e. from the above link)?

I did it with an Access Key created in IAM.
More precisely, I created it with CLI rather than console, but I don't think there is essentially a difference.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey_CLIAPI

**Comment by hiroo-kitamura** [comment]
Thank you for the answer.

> 1.What is the version of cert-manager vended by OpenShift?

cert-manager Operator for Red Hat OpenShift
v1.11.4

> 2.What version of the aws-privateca-issuer plugin are you using?

v1.2.5

> 3.What is the IAM policy associated with the Access Key you are using?

The following policy is assigned to the IAM user.
I have configured settings what is listed in [Configuration](https://github.com/cert-manager/aws-privateca-issuer/blob/main/README.md#configuration).

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "awspcaissuer",
      "Action": [
        "acm-pca:DescribeCertificateAuthority",
        "acm-pca:GetCertificate",
        "acm-pca:IssueCertificate"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:acm-pca:<region>:<account_id>:certificate-authority/<resource_id>"
    }
  ]
}
```

**Comment by hiroo-kitamura** [comment]
I've done some additional verification and will share it.
I've checked to see if there was any problem with the connectivity from aws-privateca-issuer's Pod to AWS environment.
After checking, there seemed to be no problem.

```
$ oc -n cert-manager get pod
NAME                                                  READY   STATUS    RESTARTS   AGE
aws-privateca-issuer-v1-1696905727-5c5dd95887-tpgpr   1/1     Running   0          3h38m
cert-manager-5fb76fbd98-wl5rp                         1/1     Running   0          3h38m
cert-manager-cainjector-fc95dff7b-hsptf               1/1     Running   0          3h38m
cert-manager-webhook-5f677fbff5-b9m6z                 1/1     Running   0          3h38m

$ oc -n cert-manager debug aws-privateca-issuer-v1-1696905727-5c5dd95887-tpgpr -t --image=amazon/aws-cli -- sh
Starting pod/aws-privateca-issuer-v1-1696905727-5c5dd95887-tpgpr-debug, command was: /manager --leader-elect -disable-approved-check
Pod IP: <mask>
If you don't see a command prompt, try pressing enter.
sh-4.2$ export AWS_ACCESS_KEY_ID=<mask>
sh-4.2$ export AWS_SECRET_ACCESS_KEY=<mask>
sh-4.2$ cd /tmp/
sh-4.2$ mkdir .aws
sh-4.2$ cat <<EOF >.aws/credentials
> [default]
> aws_access_key_id = ${AWS_ACCESS_KEY_ID}
> aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
> EOF
sh-4.2$ aws iam get-policy --policy-arn "<mask>"
{
    "Policy": {
        "Arn": "<mask>",
...snip...
    }
}
```

**Comment by anufreichik1** [comment]
Thank you for update on this issue with the AWS Private CA Issuer plugin. We will review your request on documentation update and respond back.

**Comment by Hamidhasan** [comment]
Thanks for trying again Hiroo, and apologies for the confusion. Happy that it worked for you!

 We investigated more after your comment, and realized that actually, both are allowed. It's the Kubernetes Secret type that supports both. Basically, the Secret type can take either plaintext String data, or base64 data. [This article describes has more information.](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/
)

From the article, here are a few examples. Our issuer works the same way, you can either use plaintext AccessKeyId/Secret in `secretData`, or base64 encoded AccessKeyId/Secret in `data`. For both, the keys would be `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

With stringData:
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: testAccessKeyId
  AWS_SECRET_ACCESS_KEY: testSecretAccessKey
```

With data: (base64)
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: dGVzdEFjY2Vzc0tleUlk
  AWS_SECRET_ACCESS_KEY: dGVzdFNlY3JldEFjY2Vzc0tleQ==
```

Also make sure to read the notes on base64 encoding and newlines, there can be issues if trying to copy paste from one tool to another with base64 encoding and trailing newlines.
