### ISSUE TITLE
[Bug]: HPA incompatible with `autoscaling/v2`

### ISSUE THREAD

**Issue by travisby** [cert-manager/aws-privateca-issuer#347]
### Describe the expected outcome

I would expect, when the cluster supports `autoscaling/v2` instead of `autoscaling/v2beta2`, that the chart would use:

```yaml
target:
  averageUtilization: xxx
  type: Utilization
```

in the HPA definition

### Describe the actual outcome

with `autoscaling/v2`, the chart produces an HPA like:

```yaml
targetAverageUtilization: xxx
```

### Steps to reproduce

`helm install --set autoscaling.enabled=true` on 1.26+ cluster

### Relevant log output

```shell
W1029 14:23:33.874689     441 warnings.go:70] unknown field "spec.metrics[0].resource.targetAverageUtilization"
W1029 14:23:33.874731     441 warnings.go:70] unknown field "spec.scaleTargetRef.namespace"
Error: 1 error occurred:
	* HorizontalPodAutoscaler.autoscaling "aws-privateca-issuer" is invalid: [spec.metrics[0].resource.target.type: Required value: must specify a metric target type, spec.metrics[0].resource.target.type: Invalid value: "": must be either Utilization, Value, or AverageValue, spec.metrics[0].resource.target.averageUtilization: Required value: must set either a target raw value or a target utilization]
```

### Version

1.4.0

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Supported Workflow Broken

### Severity

Severity 3

**Comment by travisby** [comment]
We can actually see where we chose between autoscaling/v2 and autoscalingv2beta2 in: https://github.com/cert-manager/aws-privateca-issuer/blob/235aa4851b8d057c05b168fee223406ac0eefadd/charts/aws-pca-issuer/templates/hpa.yaml#L2-L6

we just need to add a similar selector around https://github.com/cert-manager/aws-privateca-issuer/blob/235aa4851b8d057c05b168fee223406ac0eefadd/charts/aws-pca-issuer/templates/hpa.yaml#L25 and https://github.com/cert-manager/aws-privateca-issuer/blob/235aa4851b8d057c05b168fee223406ac0eefadd/charts/aws-pca-issuer/templates/hpa.yaml#L31

This deprecation is noted in https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125

**Comment by travisby** [comment]
https://github.com/cert-manager/aws-privateca-issuer/pull/271 already exists to fix the second error, that `namespace` is not meant to be there either

**Comment by HanleyYin** [comment]
Thank you for raising this issue with the AWS Private CA Issuer plugin. We will review your submission and respond back to you here as soon as possible.

**Comment by amibhi** [comment]
Hi, I have re-based #271 and updated `hpa.yaml` to use the appropriate target utilization format based on `autoscaling` version. PR comments show that the changes worked when using `autoscaling/v2beta1` for K8s v1.22.17 as well as `autoscaling/v2` for K8s v1.27.1. Full testing worklog is attached. ([HPA worklog.md](https://github.com/user-attachments/files/17837878/HPA.worklog.md))

Test workflow is now running on the PR, I will get a team member to approve and merge the PR Thursday morning EST. Let us know if there are any other questions or concerns, otherwise I think we can close this issue!

**Comment by amibhi** [comment]
#271 is now merged, closing this issue.
