### ISSUE TITLE
[Feature Request]: Increase default duration of certificates

### ISSUE THREAD

**Issue by sule26** [cert-manager/aws-privateca-issuer#349]
### Describe why this change is needed

A shorter certificate duration means certificates will expire more quickly, requiring more frequent renewals. In AWS, each renewal involves signing a new certificate, which can lead to higher costs due to the increased number of certificate issuances.

### Describe solutions and alternatives considered (optional)

Increase `DEFAULT_DURATION` for 90 days [here](https://github.com/cert-manager/aws-privateca-issuer/blob/235aa4851b8d057c05b168fee223406ac0eefadd/pkg/aws/pca.go#L40)

**Comment by bmsiegel** [comment]
https://cert-manager.io/docs/usage/certificate/

Here is the spec for a Certificate. You can configure this using the `Duration` field. Is there a specific use case you're targeting with an increased default?

**Comment by sule26** [comment]
@bmsiegel  I want cert-manager to automatically create a certificate whenever I set the annotations in the ingress. Currently, I'm using Let’s Encrypt, which creates certificates with a 90-day duration. However, with aws-privateca-issuer, the certificates last only 30 days. This requires a new certificate to be signed every 20 days, as cert-manager renews 10 days before expiration.

**Comment by bmsiegel** [comment]
Is there any way to configure the validity of that certificate?

**Comment by sule26** [comment]
@bmsiegel Worked! Thanks! 

I just wonder why such a low duration is set as the default. I Think it should be at least 90 days.
