### ISSUE TITLE
[Bug]: Cross account using the AWS Private CA issuer to request certificate hit one error: acm-pca:IssueCertificate

### ISSUE THREAD

**Issue by czduanqi2009** [cert-manager/aws-privateca-issuer#351]
### Describe the expected outcome

Expected results: can issue certificates

Question here: **### Does the AWS Private CA issuer support cross account to request certificate from AWS Private CA?**

### Describe the actual outcome

The real thing:
Hit one error in the aws-pca-issuer pod: 
{"level":"error","ts":"2024-10-31T08:43:19Z","logger":"controllers.CertificateRequest","msg":"failed to request certificate from PCA","certificaterequest":{"name":"cismt-app-tls-qgw5f","namespace":"cismt-app-ext-devhammer"},"error":"operation error ACM PCA: IssueCertificate, https response error StatusCode: 400, RequestID: fab4108c-2a79-4ebc-ab69-54d616084643, api error AccessDeniedException: User: arn:aws:sts::677467515554:assumed-role/cismt-cchmt110hammer-apca-issuer-us-east-1/1730364106525453561 is not authorized to perform: acm-pca:IssueCertificate on resource: arn:aws:acm-pca:us-east-1:640208425487:certificate-authority/240db9f4-5c10-4744-9aa7-2997cd0f3b46 because no resource-based policy allows the acm-pca:IssueCertificate action","stacktrace":"github.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*CertificateRequestReconciler).Reconcile\n\t/workspace/pkg/controllers/certificaterequest_controller.go:170\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.2/pkg/internal/controller/controller.go:222"}

### Version

cert-manager: 1.8.2

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Authentication Issue

### Severity

Severity 1

**Comment by amibhi** [comment]
Thank you for raising this issue. Can you confirm that the policy of IAM user: arn:aws:sts::677467515554:assumed-role/cismt-cchmt110hammer-apca-issuer-us-east-1/1730364106525453561 has the following permissions:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "awspcaissuer",
      "Action": [
        "acm-pca:DescribeCertificateAuthority",
        "acm-pca:GetCertificate",
        "acm-pca:IssueCertificate"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:acm-pca:us-east-1:640208425487:certificate-authority/240db9f4-5c10-4744-9aa7-2997cd0f3b46"
    }
  ]
}
```

**Comment by bp-kevin-means** [comment]
I also have this exact same behavior.

I have tried to use pod identity, and IRSA, and I get the same issue as above when trying to use a cross account CA that is shared via RAM share.

**Comment by bmsiegel** [comment]
I just set up the pca issuer with a cross account CA and was able to issue a certificate. Please verify that the RAM share you're using provides permissions to the correct privateca template: https://github.com/cert-manager/aws-privateca-issuer?tab=readme-ov-file#mapping-cert-manager-usage-types-to-aws-pca-template-arns

**Comment by bp-kevin-means** [comment]
Thank you for the quick reply! 

Yes it turns out I was using the wrong template type.  On the main account that owns the private ca resource, it has freedom to use whatever template it chooses, but when I RAM shared it, the default allowed permission on all cross accounts only allow me to issue certs using the acm-pca:::template/EndEntityCertificate/V1

As for my Ingress Controller on cross accounts, i had to add the annotation

`    cert-manager.io/usages: "server auth,client auth`

After that it worked, thank you.

**Comment by czduanqi2009** [comment]
Hi @amibhi, yes, the permission you mentioned is there.
![image](https://github.com/user-attachments/assets/a9edfad9-9a2e-40e1-8dcf-f3d0eb94aa34)

But now I changed to use RAM and also add usages section to the certificate.yaml file. Now it works fine.

**Comment by bmsiegel** [comment]
Going to close this issue, please reopen if you're still having issues.
