### ISSUE TITLE
no matches for kind "Certificate" in version "cert-manager.io/v1"

### ISSUE THREAD

**Issue by vinycoolguy2015** [cert-manager/aws-privateca-issuer#39]
no matches for kind "Certificate" in version "cert-manager.io/v1"

**Comment by jniebuhr** [comment]
Hello, could you provide some additional information on what you're trying to do?

**Comment by vinycoolguy2015** [comment]
Trying to follow https://aws.amazon.com/blogs/security/tls-enabled-kubernetes-clusters-with-acm-private-ca-and-amazon-eks-2/  and it's failing at Request the certificate step

**Comment by jniebuhr** [comment]
Did you install cert-manager? It seems like you're missing the CRD for it. It's right above installing the AWS Private CA Issuer in the blog post.

**Comment by vinycoolguy2015** [comment]
Closing issue
