### ISSUE TITLE
Operation error STS: GetCallerIdentity issue with Unit Tests issue with Region

### ISSUE THREAD

**Issue by sepulworld** [cert-manager/aws-privateca-issuer#54]
Trying to run local unit tests but seeing this error in aws-privateca-issuer-controller-manager pod

```
{"level":"error","ts":1631654584.4164567,"logger":"controllers.GenericIssuer","msg":"failed to sts.GetCallerIdentity","genericissuer":"/pca-cluster-issuer-ec","error":"operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*GenericIssuerReconciler).Reconcile\n\t/workspace/pkg/controllers/genericissuer_controller.go:92\ngithub.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*AWSPCAClusterIssuerReconciler).Reconcile\n\t/workspace/pkg/controllers/awspcaclusterissuer_controller.go:57\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
```

**Comment by bmsiegel** [comment]
Thank you for raising this issue with the AWS Private CA Issue plugin. We have reviewed your submission and replicated the issue you raised. The issue has been prioritized with our support and engineering teams. We will reach out to you if we have additional questions and will provide a notification when the issue is resolved.

**Comment by bmsiegel** [comment]
This is a known issue that we currently have with the issuer plugin. There are two things you'll need to do to fix this issue

1. Checkout the cleanup branch (see this PR: https://github.com/cert-manager/aws-privateca-issuer/pull/53)
`git fetch -a`
`git checkout cleanup`

2. We recommend using an IAM User with the plugin currently. See instructions here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey. Your IAM User will need to have at minimum permissions listed here: https://github.com/cert-manager/aws-privateca-issuer#configuration
`export AWS_SECRET_ACCESS_KEY=<Secret Access Key you generated>`
`export AWS_ACCESS_KEY_ID=<Access Key you generated>`

After doing these two steps, I was able to run the local tests after recreating your issue. Please let us know if you are successful!

**Comment by sepulworld** [comment]
Interesting! 

I fixed the issue by patching the manager pod with

```
env:
    - name: AWS_REGION
      value: "us-east-1"
```

Let me try your fix by rebasing the open PR you referenced.

**Comment by sepulworld** [comment]
Looks good after applying patch above. I see now where it adds the Region to the spec.
