### ISSUE TITLE
Known Issue: STS GetCallerIdentity failing because of a region not specified bug

### ISSUE THREAD

**Issue by solonish** [cert-manager/aws-privateca-issuer#57]
There is currently a known issue with the plugin that is preventing certificate issuance due to STS GetCallerIdentity failing because of a region not specified bug, regardless of whether a region was specified or not (https://github.com/cert-manager/aws-privateca-issuer/issues/54). There is an existing pull request to fix this (https://github.com/cert-manager/aws-privateca-issuer/pull/53), but we are holding off on accepting any pull requests until our testing is redesigned. To fix this issue until then, please checkout the cleanup branch by running

```
git fetch -a
git checkout cleanup

```
Also, please be sure you are using the plugin with an IAM user, as that is the most reliable workflow https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey
This user must have minimum permissions listed here: https://github.com/cert-manager/aws-privateca-issuer#configuration

```
export AWS_SECRET_ACCESS_KEY=<Secret Access Key you generated>
export AWS_ACCESS_KEY_ID=<Access Key you generated>

```

**Comment by divyansh-gupta** [comment]
A new release v1.0.0 has been cut that resolves this issue.
