### ISSUE TITLE
Access via IAM roles for service account

### ISSUE THREAD

**Issue by dejwsz** [cert-manager/aws-privateca-issuer#67]
### Describe why this change is needed

Currently awspca configuration needs creating a dedicated IAM user with proper access and define a secret with access key - but since it is used in EKS it would be better to use dedicated service account with assigned IAM policy. It would be more natural way I think to integrate it. How do you think? (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

**Comment by Varunvallabhan52** [comment]
Thank you for raising this enhancement request with the AWS Private CA Issue plugin. We do support IAM Role for Service Accounts(IRSA) as mentioned in the [Readme](https://github.com/cert-manager/aws-privateca-issuer#authentication).  Please refer this [example](https://aws.amazon.com/blogs/containers/setting-up-end-to-end-tls-encryption-on-amazon-eks-with-the-new-aws-load-balancer-controller/) for steps on how to do this. We have resolved the query and are closing the issue. Please reopen if you have any issues or questions.

**Comment by dejwsz** [comment]
OK thanks, I missed it somehow, I will look at it.
