### ISSUE TITLE
Known Issue: Certificates with Validity Duration under 24h failing to Issue

### ISSUE THREAD

**Issue by bmsiegel** [cert-manager/aws-privateca-issuer#71]
There is currently an issue where certificate requests with validity duration < 24h will fail to issue because of a division by 24 and cast to int64, resulting in 0 for the validity field. This results in an `api error` from PCA because PCA requires validity is not 0.

Please see #69 for more details.

While we work to cut a release to fix this change (#70), please use validity durations greater than 24h.

**Comment by divyansh-gupta** [comment]
A new release v1.0.0 has been cut that resolves this issue.
