### ISSUE TITLE
[Bug]: Bash end of file errors with new testing

### ISSUE THREAD

**Issue by sepulworld** [cert-manager/aws-privateca-issuer#92]
### Describe the expected outcome

make cluster runs with no errors locally on MacOS running Bash 5.x

### Describe the actual outcome

make cluster
```
RUNNING=$(docker inspect -f '{{.State.Running}}' "kind-registry" 2>/dev/null || true)
if [ "$RUNNING" != 'true' ]; then
bash: -c: line 2: syntax error: unexpected end of file
```

### Steps to reproduce

MacOS 11.6
```
$ bash --version
bash --version
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
```

### Version

0.3.1 (Latest)

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Broken Testing Infrastructure

### Severity

Severity 4

**Comment by KyleBS** [comment]
Thank you for raising this issue with the AWS Private CA Issue plugin. We will review your submission and respond back to you here as soon as possible

**Comment by sepulworld** [comment]
It appears to be some missing newline characters; ```\```

**Comment by KyleBS** [comment]
Alright, I can confirm that I'm seeing the same issue:
```
$ make cluster
/Users/schulthe/git/aws-privateca-issuer/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
/Users/schulthe/git/aws-privateca-issuer/bin/golangci-lint run --timeout 10m
/Users/schulthe/git/aws-privateca-issuer/bin/golint ./...
go build \
	-ldflags="-X github.com/cert-manager/aws-privateca-issuer/pkg/api/injections.PlugInVersion=v1.0.0" \
	-o bin/manager main.go
RUNNING=$(docker inspect -f '{{.State.Running}}' "kind-registry" 2>/dev/null || true)
if [ "$RUNNING" != 'true' ]; then
bash: -c: line 2: syntax error: unexpected end of file
make: *** [create-local-registry] Error 2
```

**Comment by solonish** [comment]
We have found the root cause to the issue.

This is caused because each line in the makefile recipe is usually executed in a separate shell instance.
.ONESHELL special target is used in the makefile to execute all the lines in the recipe in a single shell.
GNU Make 3.81 does not support .ONESHELL, but 3.82+ does.
So upgrading GNU make will solve this issue.

**Comment by anbaig** [comment]
Provided a readme update to make this requirement more clear. https://github.com/cert-manager/aws-privateca-issuer/pull/104

**Comment by anbaig** [comment]
If you continue to run into issues after upgrading, please open a new issue :)
