### ISSUE TITLE
[Feature Request]: Ability to set PathLength for Sub CA certificates

### ISSUE THREAD

**Issue by anbaig** [cert-manager/aws-privateca-issuer#98]
### Describe why this change is needed

With this PR https://github.com/cert-manager/aws-privateca-issuer/pull/55 we are introducing the ability to issue subCA certificate when the `isCA` flag is toggled. This is a feature request to add the ability to modify the subCA template ARN to use something besides a path length of zero. 

### Describe solutions and alternatives considered (optional)

This could possibly be done as a flag set on the issuer, that when set, is evaluated and used to set the appropriate template arn when issuing the subCA certificate.

**Comment by divyansh-gupta** [comment]
We opened this issue to gauge interest from users of this plugin. There hasn't been any feedback but please re-open and comment if you need this feature.
